[View in Colaboratory](https://colab.research.google.com/github/abhigoogol/Caavo-Computer-Vision-Challenge/blob/master/Caavo_Computer_Vision_Challenge.ipynb)

In [0]:
#@title Default title text
!pip install http://download.pytorch.org/whl/cu75/torch-0.3.0.post4-cp36-cp36m-linux_x86_64.whl 
!pip install torchvision
!pip install fastai
!apt update && apt install -y libsm6 libxext6

You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Hit:1 http://security.ubuntu.com/ubuntu artful-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu artful InRelease
Hit:3 http://archive.ubuntu.com/ubuntu artful-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu artful-backports InRelease
Reading package lists... Done
Building dependency tree       
Reading state information... Done
12 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libsm6 is already the newest version (2:1.2.2-1).
libxext6 is already the newest version (2:1.3.3-1).
0 upgraded, 0 newly installed, 0 to remove and 12 not upgraded.


In [0]:
!curl -O http://files.fast.ai/models/weights.tgz
!tar zxvf weights.tgz
!cp -r weights /usr/local/lib/python3.6/dist-packages/fastai/

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1140M  100 1140M    0     0  16.7M      0  0:01:08  0:01:08 --:--:-- 19.0M
weights/
weights/wrn_50_2f.pth
weights/resnext_101_32x4d.pth
weights/resnext_101_64x4d.pth
weights/inceptionresnetv2-d579a627.pth
weights/inceptionv4-97ef9c30.pth
weights/resnext_50_32x4d.pth


In [0]:
!wget https://s3-ap-southeast-1.amazonaws.com/he-public-data/dataset52bd6ce.zip

--2018-04-20 15:58:17--  https://s3-ap-southeast-1.amazonaws.com/he-public-data/dataset52bd6ce.zip
Resolving s3-ap-southeast-1.amazonaws.com (s3-ap-southeast-1.amazonaws.com)... 52.219.32.41
Connecting to s3-ap-southeast-1.amazonaws.com (s3-ap-southeast-1.amazonaws.com)|52.219.32.41|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 646261977 (616M) [binary/octet-stream]
Saving to: ‘dataset52bd6ce.zip.1’

dataset52bd6ce.zip.  15%[==>                 ]  92.76M  9.70MB/s    eta 4m 14s 

dataset52bd6ce.zip. 100%[===================>] 616.32M  13.0MB/s    in 86s     

2018-04-20 15:59:43 (7.18 MB/s) - ‘dataset52bd6ce.zip.1’ saved [646261977/646261977]



In [0]:
#!rm -rf dataset/

In [0]:
!unzip dataset52bd6ce.zip

Archive:  dataset52bd6ce.zip
replace dataset/sample_submissioin.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: ^C


In [0]:
!ls -la

total 2429704
drwxr-xr-x 1 root root       4096 Apr 20 15:58 .
drwxr-xr-x 1 root root       4096 Apr 20 15:14 ..
drwx------ 4 root root       4096 Apr 20 15:20 .cache
drwxr-xr-x 3 root root       4096 Apr 20 15:20 .config
drwxr-xr-x 1 root root       4096 Apr 11 21:57 datalab
drwxrwxr-x 7 root root       4096 Apr 20 15:31 dataset
-rw-r--r-- 1 root root  646261977 Apr 14 07:27 dataset52bd6ce.zip
-rw-r--r-- 1 root root  646261977 Apr 14 07:27 dataset52bd6ce.zip.1
drwxr-xr-x 4 root root       4096 Apr 20 15:15 .forever
drwxr-xr-x 5 root root       4096 Apr 20 15:20 .ipython
drwxr-xr-x 2 root root       4096 Apr 20 15:34 .jupyter
drwx------ 3 root root       4096 Apr 20 15:15 .local
drwx------ 3 root root       4096 Apr 20 15:31 .nv
-rw------- 1 root root       1024 Apr 20 15:15 .rnd
drwxr-xr-x 3 root root       4096 Apr 20 15:31 .torch
drwxrwxr-x 2 1001 1001       4096 Nov  4 13:00 weights
-rw-r--r-- 1 root root 1195411318 Apr 20 15:57 weights.tgz


In [0]:
import os
import random
import math
import shutil

In [2]:
PATH = "dataset/train/"
c_f = os.listdir(PATH)

r_img = []
r = []
for i in c_f:
    images = len(os.listdir(PATH + i))
    r = random.sample(range(1, images), math.floor(images * .1))
    r_img.append(r)
    
valid = 'dataset/valid/'
subfolder_names = []
for subfolder_name in c_f:
    if not os.path.exists(valid + subfolder_name):
        os.makedirs(os.path.join(valid, subfolder_name))
print(os.listdir())
print(os.listdir(valid))

f_set = []
for i, j in zip(c_f, r_img):
    files = os.listdir(PATH + i)
    temp = []
    for k in j:
        temp.append(files[k])
    f_set.append(temp)

for i, p in zip(f_set, c_f):
    for j in i:
        shutil.move(PATH + str(p) +'/' + str(j), valid + str(p) +'/')
    print('moving...' + PATH + str(p) +'/' + ' to ' + valid + str(p) +'/')
#         print(train + str(p) +'/' + str(j))
#         print(valid + str(p) +'/')
#         print(j, p)

['datalab', 'weights', '.rnd', 'weights.tgz', 'train.zip', '.config', '.forever', '.ipython', 'test.zip', '.local', 'dataset', '.cache', 'sample_submission.csv.zip']
['Cleavers', 'Maize', 'Small-flowered Cranesbill', 'Scentless Mayweed', 'Fat Hen', 'Charlock', 'Common wheat', 'Sugar beet', 'Loose Silky-bent', 'Black-grass', 'Shepherds Purse', 'Common Chickweed']
moving...dataset/train/Cleavers/ to dataset/valid/Cleavers/
moving...dataset/train/Maize/ to dataset/valid/Maize/
moving...dataset/train/Small-flowered Cranesbill/ to dataset/valid/Small-flowered Cranesbill/
moving...dataset/train/Scentless Mayweed/ to dataset/valid/Scentless Mayweed/
moving...dataset/train/Fat Hen/ to dataset/valid/Fat Hen/
moving...dataset/train/Charlock/ to dataset/valid/Charlock/
moving...dataset/train/Common wheat/ to dataset/valid/Common wheat/
moving...dataset/train/Sugar beet/ to dataset/valid/Sugar beet/
moving...dataset/train/Loose Silky-bent/ to dataset/valid/Loose Silky-bent/
moving...dataset/train/

In [0]:
!ls -la dataset/

total 920
drwxrwxr-x  7 root root   4096 Apr 20 15:31 .
drwxr-xr-x  1 root root   4096 Apr 20 15:58 ..
drwxr-xr-x  2 root root   4096 Apr 20 15:31 models
-rw-rw-r--  1 root root    262 Apr 14 12:39 sample_submissioin.csv
drwxrwxr-x  2 root root 909312 Apr 13 22:58 test
drwxr-xr-x 14 root root   4096 Apr 20 15:38 tmp
drwxrwxr-x 17 root root   4096 Apr 13 23:06 train
drwxr-xr-x 17 root root   4096 Apr 20 15:29 valid


In [0]:
from fastai.imports import *

from fastai.transforms import *
from fastai.conv_learner import *
from fastai.model import *
from fastai.dataset import *
from fastai.sgdr import *
from fastai.plots import *

# **Resnet34**

In [0]:
PATH = 'dataset/'
sz=150
arch=resnet34
# bs=12

In [5]:
print(torch.cuda.is_available())
print(torch.backends.cudnn.enabled)

True
True


In [0]:
data = ImageClassifierData.from_paths(PATH, tfms=tfms_from_model(arch, sz), test_name='test')
learn = ConvLearner.pretrained(arch, data, precompute=True)
learn.fit(0.02, 5)

In [0]:
tfms = tfms_from_model(arch, 
                       sz, 
                       aug_tfms=transforms_side_on)

In [0]:
data = ImageClassifierData.from_paths(PATH, tfms=tfms, test_name='test')
learn = ConvLearner.pretrained(arch, data, precompute=True, ps=0.5)
# learn.fit(1e-2, 10)

In [0]:
learn.fit(1e-2, 5)

[0.      1.28208 1.26069 0.58549]


[1.      1.30529 1.253   0.59155]
[2.      1.25399 1.25172 0.58903]
  0%|          | 4/876 [00:00<01:28,  9.86it/s, loss=1.26]

[3.      1.25858 1.25243 0.59266]
[4.      1.25939 1.24677 0.59362]



In [0]:
learn.precompute=False
# learn.fit(1e-2, 3, cycle_len=1)

In [0]:
# learn.save('224_lastlayer')
learn.load('224_lastlayer')

In [0]:
learn.unfreeze()

In [0]:
lr=np.array([1e-4,1e-3,1e-2])

In [0]:
learn.fit(lr, 2, cycle_len=1, cycle_mult=2)

[0.      1.32497 1.22363 0.60637]


[1.      1.26417 1.1602  0.62899]
[2.      1.14723 1.13825 0.63536]



In [0]:
learn.save('224_lastlayer')

In [0]:
learn.load('224_lastlayer')

# Save file to local machine

In [0]:
from google.colab import files

In [0]:
files.download('dataset/models/224_lastlayer.h5')

# uploaded = files.upload() 
# then browse, select the files. It's then uploaded

# uploaded is now a dict containing "filename" -> Content

# Prediction

In [0]:
log_preds, y = learn.TTA(is_test=True)

In [0]:
probs = np.exp(log_preds)
preds = np.argmax(probs, axis=1)
preds

array([ 8,  1,  9, ..., 11,  2,  9])

In [0]:
df = pd.DataFrame(preds)
df.columns = ['category']

In [0]:
df.insert(0, 'image_name', [o[5:] for o in data.test_ds.fnames])

In [0]:
df.head()

id  category
0   n03221540_3813_0.jpg         8
1  n04531873_20316_0.jpg         1
2   n04355511_4582_0.jpg         9
3  n03817647_19496_0.jpg         9
4      n02811719_5_0.jpg         5

In [0]:
df.to_csv('./submission.csv', index=False)

In [0]:
# !rm -f submission.csv
!ls -la

total 2430192
drwxr-xr-x 1 root root       4096 Apr 20 21:12 .
drwxr-xr-x 1 root root       4096 Apr 20 15:14 ..
drwx------ 4 root root       4096 Apr 20 15:20 .cache
drwxr-xr-x 3 root root       4096 Apr 20 15:20 .config
drwxr-xr-x 1 root root       4096 Apr 11 21:57 datalab
drwxrwxr-x 7 root root       4096 Apr 20 15:31 dataset
-rw-r--r-- 1 root root  646261977 Apr 14 07:27 dataset52bd6ce.zip
-rw-r--r-- 1 root root  646261977 Apr 14 07:27 dataset52bd6ce.zip.1
drwxr-xr-x 4 root root       4096 Apr 20 15:15 .forever
drwxr-xr-x 5 root root       4096 Apr 20 15:20 .ipython
drwxr-xr-x 2 root root       4096 Apr 20 15:34 .jupyter
drwx------ 3 root root       4096 Apr 20 15:15 .local
drwx------ 3 root root       4096 Apr 20 15:31 .nv
-rw------- 1 root root       1024 Apr 20 15:15 .rnd
-rw-r--r-- 1 root root     498167 Apr 20 21:12 submission.csv
drwxr-xr-x 3 root root       4096 Apr 20 15:31 .torch
drwxrwxr-x 2 1001 1001       4096 Nov  4 13:00 weights
-rw-r--r-- 1 root root 1195411318 Apr 

In [0]:
files.download('submission.csv')